version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=lista_compras
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '30306:3306'
    volumes:
      - db:/var/lib/mysql2
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local